package vista;

import Controlador.Ctrl_Cliente;
import dto.Dto_Cliente;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author jorge
 */
public class InterCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterProducto
     */
    public InterCliente() {
        initComponents();
        //this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Cliente");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_idcliente = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_rfc = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_estatus = new javax.swing.JTextField();
        jButton1_Guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_idusuarioalta = new javax.swing.JTextField();
        jLabel1_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Id Cliente:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("RFC:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Direccion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Telefono:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Estatus:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txt_idcliente.setBackground(new java.awt.Color(255, 255, 255));
        txt_idcliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_idcliente.setForeground(new java.awt.Color(0, 0, 0));
        txt_idcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idclienteActionPerformed(evt);
            }
        });
        txt_idcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idclienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_idcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        txt_rfc.setBackground(new java.awt.Color(255, 255, 255));
        txt_rfc.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_rfc.setForeground(new java.awt.Color(0, 0, 0));
        txt_rfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rfcKeyPressed(evt);
            }
        });
        getContentPane().add(txt_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 0));
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        txt_direccion.setBackground(new java.awt.Color(255, 255, 255));
        txt_direccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(0, 0, 0));
        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_direccionKeyPressed(evt);
            }
        });
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 170, -1));

        txt_telefono.setBackground(new java.awt.Color(255, 255, 255));
        txt_telefono.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 0));
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, -1));

        txt_estatus.setBackground(new java.awt.Color(255, 255, 255));
        txt_estatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_estatus.setForeground(new java.awt.Color(0, 0, 0));
        txt_estatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_estatusKeyPressed(evt);
            }
        });
        getContentPane().add(txt_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, -1));

        jButton1_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton1_Guardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1_Guardar.setForeground(new java.awt.Color(0, 0, 0));
        jButton1_Guardar.setText("Guardar");
        jButton1_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Id usuario alta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txt_idusuarioalta.setBackground(new java.awt.Color(255, 255, 255));
        txt_idusuarioalta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_idusuarioalta.setForeground(new java.awt.Color(0, 0, 0));
        txt_idusuarioalta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idusuarioaltaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_idusuarioalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, -1));

        jLabel1_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel1_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GuardarActionPerformed
        
    Cliente cliente = new Cliente();
    Ctrl_Cliente controlCliente = new Ctrl_Cliente();  
    controlCliente.guardarCliente(cliente, txt_idcliente, txt_nombre, txt_rfc, txt_email, txt_direccion, txt_telefono, txt_idusuarioalta, txt_estatus);
    }//GEN-LAST:event_jButton1_GuardarActionPerformed

    private void txt_idclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idclienteActionPerformed

    private void txt_idclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idclienteKeyPressed
        // TODO add your handling code here:      
        //ID PRODUCTO

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_nombre.requestFocus();
        }
    }//GEN-LAST:event_txt_idclienteKeyPressed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        //Nombre

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_rfc.requestFocus();
        }
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        //Descripcion

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_direccion.requestFocus();
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyPressed
        //Proovedor

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_telefono.requestFocus();
        }
    }//GEN-LAST:event_txt_direccionKeyPressed

    private void txt_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyPressed
        //Stock

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_idusuarioalta.requestFocus();
        }
    }//GEN-LAST:event_txt_telefonoKeyPressed

    private void txt_estatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_estatusKeyPressed
        //Estatus

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            jButton1_GuardarActionPerformed(null); // Llama al método del botón
        }
    }//GEN-LAST:event_txt_estatusKeyPressed

    private void txt_rfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rfcKeyPressed
        //Nombre

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_email.requestFocus();
        }
    }//GEN-LAST:event_txt_rfcKeyPressed

    private void txt_idusuarioaltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idusuarioaltaKeyPressed
        //usuario alta

        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            txt_estatus.requestFocus();
        }
    }//GEN-LAST:event_txt_idusuarioaltaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_wallpaper;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_estatus;
    private javax.swing.JTextField txt_idcliente;
    private javax.swing.JTextField txt_idusuarioalta;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_rfc;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    //Metodo para limpiar los campos
    private void Limpiar() {
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_idcliente.setText("");
        txt_rfc.setText("");
        txt_email.setText("");
        txt_direccion.setText("");
        txt_estatus.setText("");
        txt_idusuarioalta.setText("");
    }
}
